### ISSUE TITLE
ERROR Could not load comparison config

### ISSUE THREAD

**Issue by atirtahirgroupdocs** [groupdocs-comparison/GroupDocs.Comparison-for-.NET-WebForms#23]
Hi,
Pulled latest commit. On successful build, when I run project. I get this "Could not load comparison config" error in browser's console. Please see details in the attached file.
[error.txt](https://github.com/groupdocs-comparison/GroupDocs.Comparison-for-.NET-WebForms/files/3565314/error.txt)

**Comment by kegor** [comment]
Hi @atirtahirgroupdocs, we were unable to reproduce this error, could you please try to remove `node_modules` and `package-lock.json` and rebuild solution?

**Comment by atirtahirgroupdocs** [comment]
@kegor it didn't work out. I removed node_modules and package-lock.json. After cleaning and rebuilding solution, same issue appears.

**Comment by kegor** [comment]
Hi @atirtahirgroupdocs, could you please share the commit hash that you are using?

**Comment by atirtahirgroupdocs** [comment]
@kegor ,
I am able to run the project. It compares source and target files successfully but it doesn't render output. All I see is differences in the right panel. There is no error in [console](http://prntscr.com/p1b5pz).
![output2](https://user-images.githubusercontent.com/15940608/64190552-15ed5a80-ce90-11e9-8161-0998cac20e6c.JPG)
![output](https://user-images.githubusercontent.com/15940608/64190554-1685f100-ce90-11e9-9a9f-97f5e0e05685.JPG)
Can you please look into this?

**Comment by kegor** [comment]
Hi @atirtahirgroupdocs, could you please attach the files on which you are getting this issue?

**Comment by atirtahirgroupdocs** [comment]
@kegor ,
I have attached the files. Please see this [screencast](https://drive.google.com/file/d/11zuAH6geI3hsoIPbK89WVQmxQxmjB88d/view?usp=sharing).
[Comparison.zip](https://github.com/groupdocs-comparison/GroupDocs.Comparison-for-.NET-WebForms/files/3573372/Comparison.zip)
