### ISSUE TITLE
Wrong application behavior and comparison output

### ISSUE THREAD

**Issue by atirtahirgroupdocs** [groupdocs-comparison/GroupDocs.Comparison-for-.NET-WebForms#25]
Please find the source and target files attached. I get different output result from this showcase project. However, output from [console application](https://github.com/groupdocs-comparison/GroupDocs.Comparison-for-.NET) shows different yet right results. 
Secondly, when I press any difference in right panel of the application (Text deleted or Text added), it doesn't reflect any appropriate change/highlight in the result/output panel. Instead, it highlight only summary page. 
[wrong output.zip](https://github.com/groupdocs-comparison/GroupDocs.Comparison-for-.NET-WebForms/files/3575934/wrong.output.zip)

This issue is raised [here](https://forum.groupdocs.com/t/document-comparison-issue/7511).

**Comment by kegor** [comment]
Hi @atirtahirgroupdocs, i think, we will ship the fix during this week.

**Comment by kegor** [comment]
Hi @atirtahirgroupdocs, the fix was included in version 0.4.6 of the  https://www.npmjs.com/package/@groupdocs.examples.angular/comparison package. Let us know if this fix works for you.

**Comment by atirtahirgroupdocs** [comment]
@kegor ,

All NuGet packages restored successfully. But when I try to run application, get [this](http://prntscr.com/p8ufuv) error.

**Comment by kegor** [comment]
Hi @atirtahirgroupdocs, could you please share the full build log?

**Comment by atirtahirgroupdocs** [comment]
Hi @kegor,  Attached is the screenshot plus log details.
![error](https://user-images.githubusercontent.com/15940608/65794780-53d55a00-e182-11e9-9847-d7bb19eff1f1.JPG)
[log.txt](https://github.com/groupdocs-comparison/GroupDocs.Comparison-for-.NET-WebForms/files/3664183/log.txt)

**Comment by kegor** [comment]
Hi @atirtahirgroupdocs, could you please additionally show/attach the following log:
![GVpuf5w6SKC3qsKoMDLb0g](https://user-images.githubusercontent.com/17431807/65856777-27c8fd00-e36b-11e9-8da1-b668496acb9c.png)

**Comment by atirtahirgroupdocs** [comment]
@kegor attached are the details.
![details](https://user-images.githubusercontent.com/15940608/65902120-11568c00-e3d3-11e9-87e9-24dbdbcfcb8e.JPG)

**Comment by kegor** [comment]
@atirtahirgroupdocs, could you please also attach the log-file mentioned in your screenshot?

**Comment by atirtahirgroupdocs** [comment]
@kegor yes sorry. I have attached it now.
[2019-10-01T07_48_57_573Z-debug.log](https://github.com/groupdocs-comparison/GroupDocs.Comparison-for-.NET-WebForms/files/3675044/2019-10-01T07_48_57_573Z-debug.log)

**Comment by kegor** [comment]
Hi @atirtahirgroupdocs, could you please try to execute following actions in the root directory of the repository:
1. Delete `node_modules` folder.
2. Execute commands `npm cache clean --force`, `npm install -g @angular/cli@latest`, `npm i`
3. Try to build solution again.

**Comment by atirtahirgroupdocs** [comment]
@kegor 
I followed the steps you shared. Attached is the output details.
[build failed.txt](https://github.com/groupdocs-comparison/GroupDocs.Comparison-for-.NET-WebForms/files/3675722/build.failed.txt)

**Comment by kegor** [comment]
Hi @atirtahirgroupdocs, could you please try to delete and re-install `node`, and then before the solution build remove `node_modules` folder again?

**Comment by kegor** [comment]
Hi @atirtahirgroupdocs, was this problem been solved?

**Comment by atirtahirgroupdocs** [comment]
@kegor yes. It seems like issue was in my environment.
